version: '2'

services:
  producer:
    restart: always

    container_name: app_producer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    environment:
      DOCKER: 1
      KAFKA_SERVERS : kafka
      KAFKA_PORT : 9092

    depends_on:
    - kafka
    - zookeeper

    entrypoint: ["python", "/app/run.py"]

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
    - "2181:2181"
    environment:
      ZOOKEEPER_PORT: 2181
      ZOOKEEPER_HOST: zookeeper
  kafka:
    restart: always
    image: wurstmeister/kafka:2.12-2.2.1
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_PORT: 9092
    ports:
    - "9092:9092"
    expose:
    - 9092
